<template>
  <v-container class="text-justify">
    <div class="text-h4 text-center font-weight-bold">Privacy Policy</div>
    <div class="text-caption font-weight-bold text-center mb-4">[Last updated: 30 June, 2021]</div>

    <div class="mb-8">
      Pulse Data Technologies Sdn. Bhd. (Company Registration number: 202221028644) (hereinafter referred to as “PDT”) offers data analytics services (“the Services”) through its Healthcare Platform called “Pulse”. The Service is offered to Healthcare providers / Hospitals (“PDT clients”). PDT through Pulse uses anonymised data of patients receiving services offered by PDT’s clients and operational data related to Leadership & Governance, Patient Safety and Quality of Care.
      For all intent and purposes, PDT would not be able to secure individual patient data from its clients database. Notwithstanding the foregoing, this Privacy Policy describes PDT’s policies and procedures on the collection, use and disclosure of information when our clients use our Service and confirms our PDT clients privacy rights and how the law protects Healthcare providers / Hospitals.
      We use all data on our Healthcare Platform to undertake analytics, artificial intelligence and machine learning research and development to improve our Service to PDT clients. By using the Service, Healthcare providers / Hospitals agree to the collection and use of information in accordance with this Privacy Policy. 
    </div>

    <div class="text-h4 font-weight-bold mb-4">Interpretation and Definitions</div>
    <div class="text-h5 font-weight-bold mb-4">Interpretation</div>
    <div class="mb-4">
      The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </div>
    <div class="text-h5 font-weight-bold mb-4">Definitions</div>
    <div class="mb-8">
      <p>For the purposes of this Privacy Policy:</p>
      <p>
        <ul>
          <li>Account means a unique account created for Healthcare providers / Hospitals to access our Service or parts of our Service.</li>
          <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li>Application means the software program called Pulse provided by PDT and downloaded by Healthcare providers / Hospitals on any electronic device.</li>
          <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Pulse Data Technologies Sdn. Bhd. (Company Registration number: 202221028644) (hereinafter referred to as “PDT”).</li>
          <li>Country refers to: Malaysia</li>
          <li>Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li>Personal Data is any information that relates to an identified or identifiable individual / patient.</li>
          <li>Service refers to the Application called Pulse.</li>
          <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li>Users means Healthcare providers / Hospitals including registered employees, the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>
      </p>
    </div>

    <div class="text-h4 font-weight-bold mb-4">Collecting and Using Data</div>
    <div class="text-h5 font-weight-bold mb-4">Types of Data Collected</div>
    <div class="text-h6 font-weight-bold mb-4">Usage Data</div>
    <div>
      <p>Usage Data is collected automatically when Healthcare Providers / Hospitals and or its registered employees (hereinafter referred to as “Users) use the Pulse Service.</p>
      <p>Usage Data may include information such as cell phones Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
      <p>When Users access the Service by or through a mobile or other device , We may collect certain information automatically, including, but not limited to, the type of mobile device Users use, Users mobile device unique ID, the IP address of Users mobile device, mobile operating system, the type of mobile Internet browser used, unique device identifiers and other diagnostic data.</p>
      <p>We may also collect information that the Users browser sends whenever Users utilise our Service or when Users access the Service by or through a mobile device.</p>
    </div>
    <div class="text-h6 font-weight-bold mb-4">Information Collected while Using the Application</div>
    <div>
      <p>While using Our Application, in order to provide features of Our Application, We may collect:</p>
      <p>
        <ul>
          <li>Information regarding Users location within the Hospital</li>
          <li>Pictures and other information from Users Device's camera and photo library uploaded as part of the Service</li>
        </ul>
      </p>
      <p>Hereinafter referred to as “Users Information” We may use this information to provide features of Our Service, to improve and customize Our Service to You. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Users own devices.</p>
      <p>Users can enable or disable access to this information at any time, through their Device settings.</p>
    </div>

    <div class="text-h5 font-weight-bold mb-4">Use of Data and Information</div>
    <div>
      <p>The Company may utilise Usage Data and User Information from Healthcare providers / Hospitals and its registered employees for the following purposes:</p>
      <p>
        <ul>
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Users Accounts: to manage Healthcare Providers / Hospitals and or its registered employees registration as a user of the Service. The Data Users provide can give Users full access to different functionalities of the Service that are available to registered Users.</li>
          <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services Healthcare Providers / Hospitals have purchased or of any other contract with Us through the Service.</li>
          <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li>To provide Healthcare Providers / Hospitals with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
          <li>To manage Healthcare Providers / Hospitals requests: To attend and manage Your requests to Us received from time to time.</li>
          <li>For business transfers: We may use Your Usage Data and Users Information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Data and Information held by Us about our Service users is among the assets transferred.</li>
          <li>For other purposes: We may use Your Usage Data and Users Information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience with our Service.</li>
        </ul>
      </p>
      <p>We may share Your Users Information and Usage Data in the following situations:</p>
      <p>
        <ul>
          <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
          <li>For business transfers: We may share or transfer Your Usage Data and Usage Information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
          <li>With Affiliates: We may share Your Usage Data and Usage Information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
          <li>With business partners: We may share Your Usage Data and Usage Information with Our business partners to offer You certain products, services or promotions.</li>
          <li>With other users: when Users share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
          <li>With Your consent: We may disclose Your Usage data and Usage Information for any other purpose with Your consent.</li>
        </ul>
      </p>
    </div>

    <div class="text-h5 font-weight-bold mb-4">Retention of Your Personal Data</div>
    <div>
      <p>The Company will retain Your Usage Data and Usage Information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use such Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
      <p>The Company will also retain Usage Data and Usage Information for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obliged to retain this data for longer time periods.</p>
    </div>

    <div class="text-h5 font-weight-bold mb-4">Transfer of Data</div>
    <div>
      <p>User information, including Usage Data and Usage Information, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction.</p>
      <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
      <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Usage Data or Usage Information will take place to an organization or a country unless there are adequate controls in place including the security of such data and other information.</p>
    </div>

    <div class="text-h5 font-weight-bold mb-4">Disclosure of Data</div>
    <div class="text-h6 font-weight-bold mb-4">Business Transactions</div>
    <div>
      <p>If the Company is involved in a merger, acquisition or asset sale, Your Usage Data and Usage Information may be transferred. We will provide notice before such Data is transferred and becomes subject to a different Privacy Policy.</p>
    </div>
    <div class="text-h6 font-weight-bold mb-4">Law enforcement</div>
    <div>
      <p>Under certain circumstances, the Company may be required to disclose Your Usage Data and Usage Information if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
    </div>
    <div class="text-h6 font-weight-bold mb-4">Other legal requirements</div>
    <div>
      <p>The Company may disclose Your Usage Data and Usage Information in the good faith and belief that such action is necessary to:</p>
      <p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
      </p>
    </div>
    <div class="text-h5 font-weight-bold mb-4">Security of Your Personal Data</div>
    <div class="mb-8">
      <p>The security of Your Usage Data and Usage Information is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Data, We cannot guarantee its absolute security.</p>
    </div>


    <div class="text-h4 font-weight-bold mb-4">Children's Privacy</div>
    <div class="mb-8">
      <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
      <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
    </div>

    <div class="text-h4 font-weight-bold mb-4">Links to Other Websites</div>
    <div class="mb-8">
      <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
      <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
    </div>

    <div class="text-h4 font-weight-bold mb-4">Changes to this Privacy Policy</div>
    <div class="mb-8">
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
      <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
      <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    </div>

    <div class="text-h4 font-weight-bold mb-4">Contact Us</div>
    <div class="mb-8">
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <p>
        <ul>
          <li>By email: vincent@pulsedt.tech</li>
        </ul>
      </p>
    </div>
  </v-container>
</template>

<script>
export default {

}
</script>

<style scoped src="@/views/privacyPolicy/privacyPolicy.css"></style>